"""Public XML-independent canonical domain and deterministic JSON serialization."""

from sema_sedd.model.domain import (
    Alarm,
    CanonicalEquipmentInterface,
    CollectionEvent,
    DataVariable,
    DefaultReport,
    EquipmentConstant,
    EquipmentInterface,
    EquipmentMetadata,
    EventReportLink,
    RemoteCommand,
    RemoteCommandParameter,
    StandardReference,
    StatusVariable,
    SupportedMessage,
    VariableFormat,
)
from sema_sedd.model.serialization import (
    MODEL_SCHEMA_VERSION,
    to_canonical_dict,
    to_canonical_json,
)
from sema_sedd.model.values import (
    CanonicalType,
    DataStructure,
    EntityReference,
    JsonArray,
    JsonObject,
    MessageDirection,
    Requiredness,
    SourceProvenance,
    StateTransition,
    UnknownExtension,
    UnresolvedReason,
    UnresolvedReference,
    WellKnownName,
    WknAuthority,
)

__all__ = [
    "MODEL_SCHEMA_VERSION",
    "Alarm",
    "CanonicalEquipmentInterface",
    "CanonicalType",
    "CollectionEvent",
    "DataStructure",
    "DataVariable",
    "DefaultReport",
    "EntityReference",
    "EquipmentConstant",
    "EquipmentInterface",
    "EquipmentMetadata",
    "EventReportLink",
    "JsonArray",
    "JsonObject",
    "MessageDirection",
    "RemoteCommand",
    "RemoteCommandParameter",
    "Requiredness",
    "SourceProvenance",
    "StandardReference",
    "StateTransition",
    "StatusVariable",
    "SupportedMessage",
    "UnknownExtension",
    "UnresolvedReason",
    "UnresolvedReference",
    "VariableFormat",
    "WellKnownName",
    "WknAuthority",
    "to_canonical_dict",
    "to_canonical_json",
]
